// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Npgsql;
using PostgreSqlCitext.AfterFix.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace PostgreSqlCitext.AfterFix.Models
{
    public partial interface IPGContextFunctions
    {
        Task<int> testcitextinAsync(string input_val, CancellationToken cancellationToken = default);
        Task<List<testcitextoutResult>> testcitextoutAsync(CancellationToken cancellationToken = default);
        Task<List<TestTextResult>> TestTextAsync(string input_val, CancellationToken cancellationToken = default);
    }
}
