// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Npgsql;
using PostgreSqlCitext.Official_20260420_Fix.TestCitextOutModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace PostgreSqlCitext.Official_20260420_Fix.TestCitextOutModels
{
    public partial interface IPGContextFunctions
    {
        Task<List<testcitextoutResult>> testcitextoutAsync(CancellationToken cancellationToken = default);
        Task<List<testtextResult>> testtextAsync(string input_val, CancellationToken cancellationToken = default);
    }
}
