// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PostgreSqlCitext.Official_20260420_Fix.TestCitextOutModels
{
    public partial class testtextResult
    {
        public string resultcolumn { get; set; }
    }
}
