// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Npgsql;
using PostgreSqlCitext.BeforeFix.TestTextModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace PostgreSqlCitext.BeforeFix.TestTextModels
{
    public partial interface IPGContextFunctions
    {
        Task<List<TestTextResult>> TestTextAsync(string input_val, CancellationToken cancellationToken = default);
    }
}
