// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Npgsql;
using PostgreSqlCitext.Official_20260420.TestCitextOutModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace PostgreSqlCitext.Official_20260420.TestCitextOutModels
{
    public partial class PGContext
    {
        private IPGContextFunctions _procedures;

        public virtual IPGContextFunctions Functions
        {
            get
            {
                if (_procedures is null) _procedures = new PGContextFunctions(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IPGContextFunctions GetFunctions()
        {
            return Functions;
        }
    }

    public partial class PGContextFunctions : IPGContextFunctions
    {
        private readonly PGContext _context;

        public PGContextFunctions(PGContext context)
        {
            _context = context;
        }

        public virtual async Task<List<testcitextoutResult>> testcitextoutAsync(, CancellationToken cancellationToken = default)
        {
            var npgsqlParameters = new []
            {
            };
            var _ = await _context.SqlQueryAsync<testcitextoutResult>("SELECT * FROM \"dbo\".\"testcitextout\" ()", npgsqlParameters, cancellationToken);

            return _;
        }

        public virtual async Task<List<testtextResult>> testtextAsync(string input_val, CancellationToken cancellationToken = default)
        {
            var npgsqlParameters = new []
            {
                new NpgsqlParameter
                {
                    ParameterName = "input_val",
                    Value = input_val ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Text,
                },
            };
            var _ = await _context.SqlQueryAsync<testtextResult>("SELECT * FROM \"dbo\".\"testtext\" (@input_val)", npgsqlParameters, cancellationToken);

            return _;
        }
    }
}
