// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Npgsql;
using PostgreSqlCitext.Official_20260420_Fix.TestCitextInModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace PostgreSqlCitext.Official_20260420_Fix.TestCitextInModels
{
    public partial interface IPGContextFunctions
    {
        Task<int> testcitextinAsync(string input_val, CancellationToken cancellationToken = default);
        Task<List<testtextResult>> testtextAsync(string input_val, CancellationToken cancellationToken = default);
    }
}
